pipeline:
  build:
    image: node:12-alpine
    environment:
      - COMMUNITY_ID=40
      - REACT_APP_ZENDESK_ORGANIZATIONS={"lawyer":360269610652,"individual":360273031591,"therapist":360282119532}
      - ZENDESK_API_URL=https://mapadoacolhimento.zendesk.com/api/v2/
      - REACT_APP_ENVIRONMENT=staging
    commands:
      - export REACT_APP_GOOGLE_CLIENT_KEY=$STAG_GOOGLE_CLIENT
      - export ZENDESK_API_TOKEN=$STGA_ZENDESK_API_TOKEN
      - export ZENDESK_API_USER=$STGA_ZENDESK_API_USER
      - yarn global add pnpm
      - pnpm i
      - pnpm m run build
    secrets: [stag_google_client, stag_zendesk_token, stag_zendesk_user]
    when:
      event: [push]

  production-build:
    image: node:12-alpine
    environment:
      - COMMUNITY_ID=40
      - REACT_APP_ZENDESK_ORGANIZATIONS={"lawyer":360269610652,"individual":360273031591,"therapist":360282119532}
      - ZENDESK_API_URL=https://mapadoacolhimento.zendesk.com/api/v2/
      - REACT_APP_ENVIRONMENT=production
    commands:
      - export REACT_APP_GOOGLE_CLIENT_KEY=$STAG_GOOGLE_CLIENT
      - export ZENDESK_API_TOKEN=$STGA_ZENDESK_API_TOKEN
      - export ZENDESK_API_USER=$STGA_ZENDESK_API_USER
      - yarn global add pnpm
      - pnpm i
      - pnpm m run build
    secrets: [stag_google_client, stag_zendesk_token, stag_zendesk_user]
    when:
      event: [tag]

  publish-stag-solidarity:
    image: plugins/docker
    repo: nossas/mapa-do-acolhimento
    group: publishing
    secrets: [docker_username, docker_password]
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]
      event: push

  publish-prod-solidarity:
    image: plugins/docker
    repo: nossas/mapa-do-acolhimento
    group: publishing
    secrets: [docker_username, docker_password]
    tags:
      - ${DRONE_TAG##v}
      - latest
    when:
      status: success
      event: tag

  # publish-stag-webhooks-registry:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-registry
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhooks-registry/Dockerfile
  #   tags:
  #     - ${DRONE_BRANCH/\//-}
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, support/*, develop]
  #     event: push

  # publish-prod-webhooks-registry:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-registry
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhooks-registry/Dockerfile
  #   tags:
  #     - ${DRONE_TAG##v}
  #     - latest
  #   when:
  #     status: success
  #     event: tag

  # publish-stag-webhooks-zendesk:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-zendesk
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhooks-zendesk/Dockerfile
  #   tags:
  #     - ${DRONE_BRANCH/\//-}
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, support/*, develop]
  #     event: push

  # publish-prod-webhooks-zendesk:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-zendesk
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhooks-zendesk/Dockerfile
  #   tags:
  #     - ${DRONE_TAG##v}
  #     - latest
  #   when:
  #     status: success
  #     event: tag

  deploy-stag-cli-zendesk-user:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webhooks/cli-zendesk-user
    group: deploying
    docker_image: nossas/mapa-do-acolhimento:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [rancher_access_key, rancher_secret_key]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]
      event: push

  deploy-stag-cli-zendesk-ticket:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webhooks/cli-zendesk-ticket
    group: deploying
    docker_image: nossas/mapa-do-acolhimento:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [rancher_access_key, rancher_secret_key]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]
      event: push

  deploy-prod-cli-zendesk-user:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webhooks/cli-zendesk-user
    docker_image: "nossas/mapa-do-acolhimento:${DRONE_TAG##v}"
    timeout: 360
    group: deploying
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  deploy-prod-cli-zendesk-ticket:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webhooks/cli-zendesk-ticket
    docker_image: "nossas/mapa-do-acolhimento:${DRONE_TAG##v}"
    timeout: 360
    group: deploying
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  deploy-stag-webhooks-solidarity-count:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webhooks/solidarity-count
    group: deploying
    docker_image: nossas/mapa-do-acolhimento:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [rancher_access_key, rancher_secret_key]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]
      event: push

  deploy-prod-webhooks-solidarity-count:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webhooks/solidarity-count
    docker_image: "nossas/mapa-do-acolhimento:${DRONE_TAG##v}"
    timeout: 360
    group: deploying
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  deploy-stag-client-solidarity:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webservers/match-otimizado
    group: deploying
    docker_image: nossas/mapa-do-acolhimento:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [rancher_access_key, rancher_secret_key]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]
      event: push

  deploy-prod-client-solidarity:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webservers/match-otimizado
    docker_image: "nossas/mapa-do-acolhimento:${DRONE_TAG##v}"
    timeout: 360
    group: deploying
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  deploy-stag-listener-solidarity:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: listeners/mapa-do-acolhimento
    group: deploying
    docker_image: nossas/mapa-do-acolhimento:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [rancher_access_key, rancher_secret_key]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]
      event: push

  deploy-prod-listener-solidarity:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: listeners/mapa-do-acolhimento
    docker_image: "nossas/mapa-do-acolhimento:${DRONE_TAG##v}"
    timeout: 360
    group: deploying
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag
  #
  # deploy-stag-webhooks-registry:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/registry
  #   group: deploying
  #   docker_image: nossas/bonde-webhooks-registry:${DRONE_BRANCH/\//-}
  #   timeout: 360
  #   confirm: true
  #   secrets: [ rancher_access_key, rancher_secret_key ]
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, develop]
  #     event: push
  #
  # deploy-prod-webhooks-registry:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/registry
  #   docker_image: "nossas/bonde-webhooks-registry:${DRONE_TAG##v}"
  #   timeout: 360
  #   group: deploying
  #   confirm: true
  #   secrets:
  #     - source: rancher_access_key_prod
  #       target: rancher_access_key
  #     - source: rancher_secret_key_prod
  #       target: rancher_secret_key
  #   when:
  #     status: success
  #     event: tag
  #
  # deploy-stag-webhooks-zendesk:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/zendesk
  #   group: deploying
  #   docker_image: nossas/bonde-webhooks-zendesk:${DRONE_BRANCH/\//-}
  #   timeout: 360
  #   confirm: true
  #   secrets: [ rancher_access_key, rancher_secret_key ]
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, develop]
  #     event: push
  # deploy-prod-webhooks-zendesk:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/zendesk
  #   docker_image: "nossas/bonde-webhooks-zendesk:${DRONE_TAG##v}"
  #   timeout: 360
  #   group: deploying
  #   confirm: true
  #   secrets:
  #     - source: rancher_access_key_prod
  #       target: rancher_access_key
  #     - source: rancher_secret_key_prod
  #       target: rancher_secret_key
  #   when:
  #     status: success
  #     event: tag
  #
  # deploy-stag-cli-mautic:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/cli-mautic
  #   group: deploying
  #   docker_image: nossas/bonde-cli-mautic:${DRONE_BRANCH/\//-}
  #   timeout: 360
  #   confirm: true
  #   secrets: [ rancher_access_key, rancher_secret_key ]
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, develop]
  #     event: push
  # deploy-prod-cli-mautic:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/cli-mautic
  #   docker_image: "nossas/bonde-cli-mautic:${DRONE_TAG##v}"
  #   timeout: 360
  #   group: deploying
  #   confirm: true
  #   secrets:
  #     - source: rancher_access_key_prod
  #       target: rancher_access_key
  #     - source: rancher_secret_key_prod
  #       target: rancher_secret_key
  #   when:
  #     status: success
  #     event: tag
  # deploy-stag-webhooks-solidarity-match:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/solidarity-match
  #   group: deploying
  #   docker_image: nossas/bonde-webhooks-solidarity-match:${DRONE_BRANCH/\//-}
  #   timeout: 360
  #   confirm: true
  #   secrets: [ rancher_access_key, rancher_secret_key ]
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, develop]
  #     event: push
  # deploy-prod-webhooks-solidarity-match:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/solidarity-match
  #   docker_image: "nossas/bonde-webhooks-solidarity-match:${DRONE_TAG##v}"
  #   timeout: 360
  #   group: deploying
  #   confirm: true
  #   secrets:
  #     - source: rancher_access_key_prod
  #       target: rancher_access_key
  #     - source: rancher_secret_key_prod
  #       target: rancher_secret_key
  #   when:
  #     status: success
  #     event: tag
  # deploy-stag-webhooks-mail:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/mail
  #   group: deploying
  #   docker_image: nossas/bonde-webhooks-mail:${DRONE_BRANCH/\//-}
  #   timeout: 360
  #   confirm: true
  #   secrets: [ rancher_access_key, rancher_secret_key ]
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, develop]
  #     event: push
  # deploy-prod-webhooks-mail:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/mail
  #   docker_image: "nossas/bonde-webhooks-mail:${DRONE_TAG##v}"
  #   timeout: 360
  #   group: deploying
  #   confirm: true
  #   secrets:
  #     - source: rancher_access_key_prod
  #       target: rancher_access_key
  #     - source: rancher_secret_key_prod
  #       target: rancher_secret_key
  #   when:
  #     status: success
  #     event: tag
